namespace Pharmacy_Managemnet_System.GUI.UC.Master_UC
{
    partial class MasterUC
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MasterUC));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.Panel1 = new System.Windows.Forms.Panel();
            this.Options_Tmr = new System.Windows.Forms.Timer(this.components);
            this.A2SAnimator1 = new A7MD_Library.NewComponent.A2SAnimator();
            this.New_Btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Save_Btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Guna2Button3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Delete_Btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Guna2Button1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Search_Btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Option_Btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Back_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DisableLockBtn = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.DisableLockBtn)).BeginInit();
            this.SuspendLayout();
            // 
            // Panel1
            // 
            this.Panel1.BackColor = System.Drawing.Color.Transparent;
            this.Panel1.Dock = System.Windows.Forms.DockStyle.Right;
            this.Panel1.Location = new System.Drawing.Point(798, 0);
            this.Panel1.Name = "Panel1";
            this.Panel1.Size = new System.Drawing.Size(12, 468);
            this.Panel1.TabIndex = 359;
            // 
            // Options_Tmr
            // 
            this.Options_Tmr.Interval = 2500;
            this.Options_Tmr.Tick += new System.EventHandler(this.Options_Tmr_Tick);
            // 
            // New_Btn
            // 
            this.New_Btn.AllowAnimations = true;
            this.New_Btn.AllowMouseEffects = true;
            this.New_Btn.AllowToggling = false;
            this.New_Btn.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.New_Btn.AnimationSpeed = 200;
            this.New_Btn.AutoGenerateColors = false;
            this.New_Btn.AutoRoundBorders = true;
            this.New_Btn.AutoSizeLeftIcon = true;
            this.New_Btn.AutoSizeRightIcon = true;
            this.New_Btn.BackColor = System.Drawing.Color.Transparent;
            this.New_Btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.New_Btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("New_Btn.BackgroundImage")));
            this.New_Btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.New_Btn.ButtonText = "جديد";
            this.New_Btn.ButtonTextMarginLeft = 0;
            this.New_Btn.ColorContrastOnClick = 45;
            this.New_Btn.ColorContrastOnHover = 45;
            this.New_Btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.New_Btn.CustomizableEdges = borderEdges1;
            this.New_Btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.New_Btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.New_Btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.New_Btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.New_Btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.New_Btn.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.New_Btn.ForeColor = System.Drawing.Color.White;
            this.New_Btn.IconLeft = null;
            this.New_Btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.New_Btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.New_Btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.New_Btn.IconMarginLeft = 11;
            this.New_Btn.IconPadding = 10;
            this.New_Btn.IconRight = ((System.Drawing.Image)(resources.GetObject("New_Btn.IconRight")));
            this.New_Btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.New_Btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.New_Btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.New_Btn.IconSize = 25;
            this.New_Btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.New_Btn.IdleBorderRadius = 33;
            this.New_Btn.IdleBorderThickness = 1;
            this.New_Btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.New_Btn.IdleIconLeftImage = null;
            this.New_Btn.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("New_Btn.IdleIconRightImage")));
            this.New_Btn.IndicateFocus = true;
            this.New_Btn.Location = new System.Drawing.Point(623, 417);
            this.New_Btn.Name = "New_Btn";
            this.New_Btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.New_Btn.OnDisabledState.BorderRadius = 35;
            this.New_Btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.New_Btn.OnDisabledState.BorderThickness = 1;
            this.New_Btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.New_Btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.New_Btn.OnDisabledState.IconLeftImage = null;
            this.New_Btn.OnDisabledState.IconRightImage = null;
            this.New_Btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.New_Btn.onHoverState.BorderRadius = 35;
            this.New_Btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.New_Btn.onHoverState.BorderThickness = 1;
            this.New_Btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.New_Btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.New_Btn.onHoverState.IconLeftImage = null;
            this.New_Btn.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("New_Btn.onHoverState.IconRightImage")));
            this.New_Btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.New_Btn.OnIdleState.BorderRadius = 35;
            this.New_Btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.New_Btn.OnIdleState.BorderThickness = 1;
            this.New_Btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.New_Btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.New_Btn.OnIdleState.IconLeftImage = null;
            this.New_Btn.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("New_Btn.OnIdleState.IconRightImage")));
            this.New_Btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.New_Btn.OnPressedState.BorderRadius = 35;
            this.New_Btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.New_Btn.OnPressedState.BorderThickness = 1;
            this.New_Btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.New_Btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.New_Btn.OnPressedState.IconLeftImage = null;
            this.New_Btn.OnPressedState.IconRightImage = null;
            this.New_Btn.Size = new System.Drawing.Size(113, 35);
            this.New_Btn.TabIndex = 363;
            this.New_Btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.New_Btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.New_Btn.TextMarginLeft = 0;
            this.New_Btn.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.New_Btn.UseDefaultRadiusAndThickness = true;
            this.New_Btn.Visible = false;
            this.New_Btn.Click += new System.EventHandler(this.New_Btn_Click);
            this.New_Btn.MouseEnter += new System.EventHandler(this.Action_Buttons_MouseHover);
            this.New_Btn.MouseLeave += new System.EventHandler(this.Action_Buttons_MouseLeave);
            this.New_Btn.MouseHover += new System.EventHandler(this.Action_Buttons_MouseHover);
            // 
            // Save_Btn
            // 
            this.Save_Btn.AllowAnimations = true;
            this.Save_Btn.AllowMouseEffects = true;
            this.Save_Btn.AllowToggling = false;
            this.Save_Btn.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.Save_Btn.AnimationSpeed = 200;
            this.Save_Btn.AutoGenerateColors = false;
            this.Save_Btn.AutoRoundBorders = true;
            this.Save_Btn.AutoSizeLeftIcon = true;
            this.Save_Btn.AutoSizeRightIcon = true;
            this.Save_Btn.BackColor = System.Drawing.Color.Transparent;
            this.Save_Btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Save_Btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save_Btn.BackgroundImage")));
            this.Save_Btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_Btn.ButtonText = "حفظ";
            this.Save_Btn.ButtonTextMarginLeft = 0;
            this.Save_Btn.ColorContrastOnClick = 45;
            this.Save_Btn.ColorContrastOnHover = 45;
            this.Save_Btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Save_Btn.CustomizableEdges = borderEdges2;
            this.Save_Btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save_Btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_Btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_Btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_Btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Save_Btn.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Save_Btn.ForeColor = System.Drawing.Color.White;
            this.Save_Btn.IconLeft = null;
            this.Save_Btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save_Btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save_Btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save_Btn.IconMarginLeft = 11;
            this.Save_Btn.IconPadding = 10;
            this.Save_Btn.IconRight = ((System.Drawing.Image)(resources.GetObject("Save_Btn.IconRight")));
            this.Save_Btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save_Btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save_Btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Save_Btn.IconSize = 25;
            this.Save_Btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Save_Btn.IdleBorderRadius = 33;
            this.Save_Btn.IdleBorderThickness = 1;
            this.Save_Btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Save_Btn.IdleIconLeftImage = null;
            this.Save_Btn.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Save_Btn.IdleIconRightImage")));
            this.Save_Btn.IndicateFocus = true;
            this.Save_Btn.Location = new System.Drawing.Point(471, 417);
            this.Save_Btn.Name = "Save_Btn";
            this.Save_Btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_Btn.OnDisabledState.BorderRadius = 35;
            this.Save_Btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_Btn.OnDisabledState.BorderThickness = 1;
            this.Save_Btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_Btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_Btn.OnDisabledState.IconLeftImage = null;
            this.Save_Btn.OnDisabledState.IconRightImage = null;
            this.Save_Btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Save_Btn.onHoverState.BorderRadius = 35;
            this.Save_Btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_Btn.onHoverState.BorderThickness = 1;
            this.Save_Btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Save_Btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Save_Btn.onHoverState.IconLeftImage = null;
            this.Save_Btn.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Save_Btn.onHoverState.IconRightImage")));
            this.Save_Btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Save_Btn.OnIdleState.BorderRadius = 35;
            this.Save_Btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_Btn.OnIdleState.BorderThickness = 1;
            this.Save_Btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Save_Btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Save_Btn.OnIdleState.IconLeftImage = null;
            this.Save_Btn.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Save_Btn.OnIdleState.IconRightImage")));
            this.Save_Btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Save_Btn.OnPressedState.BorderRadius = 35;
            this.Save_Btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Save_Btn.OnPressedState.BorderThickness = 1;
            this.Save_Btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Save_Btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Save_Btn.OnPressedState.IconLeftImage = null;
            this.Save_Btn.OnPressedState.IconRightImage = null;
            this.Save_Btn.Size = new System.Drawing.Size(113, 35);
            this.Save_Btn.TabIndex = 364;
            this.Save_Btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save_Btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save_Btn.TextMarginLeft = 0;
            this.Save_Btn.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Save_Btn.UseDefaultRadiusAndThickness = true;
            this.Save_Btn.Visible = false;
            this.Save_Btn.Click += new System.EventHandler(this.Save_Btn_Click);
            this.Save_Btn.MouseEnter += new System.EventHandler(this.Action_Buttons_MouseHover);
            this.Save_Btn.MouseLeave += new System.EventHandler(this.Action_Buttons_MouseLeave);
            this.Save_Btn.MouseHover += new System.EventHandler(this.Action_Buttons_MouseHover);
            // 
            // Guna2Button3
            // 
            this.Guna2Button3.AllowAnimations = true;
            this.Guna2Button3.AllowMouseEffects = true;
            this.Guna2Button3.AllowToggling = false;
            this.Guna2Button3.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.Guna2Button3.AnimationSpeed = 200;
            this.Guna2Button3.AutoGenerateColors = false;
            this.Guna2Button3.AutoRoundBorders = true;
            this.Guna2Button3.AutoSizeLeftIcon = true;
            this.Guna2Button3.AutoSizeRightIcon = true;
            this.Guna2Button3.BackColor = System.Drawing.Color.Transparent;
            this.Guna2Button3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button3.BackgroundImage")));
            this.Guna2Button3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button3.ButtonText = "جديد";
            this.Guna2Button3.ButtonTextMarginLeft = 0;
            this.Guna2Button3.ColorContrastOnClick = 45;
            this.Guna2Button3.ColorContrastOnHover = 45;
            this.Guna2Button3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Guna2Button3.CustomizableEdges = borderEdges3;
            this.Guna2Button3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Guna2Button3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Guna2Button3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Guna2Button3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Guna2Button3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Guna2Button3.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Guna2Button3.ForeColor = System.Drawing.Color.White;
            this.Guna2Button3.IconLeft = null;
            this.Guna2Button3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Guna2Button3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Guna2Button3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Guna2Button3.IconMarginLeft = 11;
            this.Guna2Button3.IconPadding = 10;
            this.Guna2Button3.IconRight = ((System.Drawing.Image)(resources.GetObject("Guna2Button3.IconRight")));
            this.Guna2Button3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Guna2Button3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Guna2Button3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Guna2Button3.IconSize = 25;
            this.Guna2Button3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button3.IdleBorderRadius = 33;
            this.Guna2Button3.IdleBorderThickness = 1;
            this.Guna2Button3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button3.IdleIconLeftImage = null;
            this.Guna2Button3.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button3.IdleIconRightImage")));
            this.Guna2Button3.IndicateFocus = true;
            this.Guna2Button3.Location = new System.Drawing.Point(319, 417);
            this.Guna2Button3.Name = "Guna2Button3";
            this.Guna2Button3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Guna2Button3.OnDisabledState.BorderRadius = 35;
            this.Guna2Button3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button3.OnDisabledState.BorderThickness = 1;
            this.Guna2Button3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Guna2Button3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Guna2Button3.OnDisabledState.IconLeftImage = null;
            this.Guna2Button3.OnDisabledState.IconRightImage = null;
            this.Guna2Button3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Guna2Button3.onHoverState.BorderRadius = 35;
            this.Guna2Button3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button3.onHoverState.BorderThickness = 1;
            this.Guna2Button3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Guna2Button3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Guna2Button3.onHoverState.IconLeftImage = null;
            this.Guna2Button3.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button3.onHoverState.IconRightImage")));
            this.Guna2Button3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button3.OnIdleState.BorderRadius = 35;
            this.Guna2Button3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button3.OnIdleState.BorderThickness = 1;
            this.Guna2Button3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Guna2Button3.OnIdleState.IconLeftImage = null;
            this.Guna2Button3.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button3.OnIdleState.IconRightImage")));
            this.Guna2Button3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Guna2Button3.OnPressedState.BorderRadius = 35;
            this.Guna2Button3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button3.OnPressedState.BorderThickness = 1;
            this.Guna2Button3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Guna2Button3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Guna2Button3.OnPressedState.IconLeftImage = null;
            this.Guna2Button3.OnPressedState.IconRightImage = null;
            this.Guna2Button3.Size = new System.Drawing.Size(113, 35);
            this.Guna2Button3.TabIndex = 365;
            this.Guna2Button3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Guna2Button3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Guna2Button3.TextMarginLeft = 0;
            this.Guna2Button3.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Guna2Button3.UseDefaultRadiusAndThickness = true;
            this.Guna2Button3.Visible = false;
            this.Guna2Button3.MouseEnter += new System.EventHandler(this.Action_Buttons_MouseHover);
            this.Guna2Button3.MouseLeave += new System.EventHandler(this.Action_Buttons_MouseLeave);
            this.Guna2Button3.MouseHover += new System.EventHandler(this.Action_Buttons_MouseHover);
            // 
            // Delete_Btn
            // 
            this.Delete_Btn.AllowAnimations = true;
            this.Delete_Btn.AllowMouseEffects = true;
            this.Delete_Btn.AllowToggling = false;
            this.Delete_Btn.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.Delete_Btn.AnimationSpeed = 200;
            this.Delete_Btn.AutoGenerateColors = false;
            this.Delete_Btn.AutoRoundBorders = true;
            this.Delete_Btn.AutoSizeLeftIcon = true;
            this.Delete_Btn.AutoSizeRightIcon = true;
            this.Delete_Btn.BackColor = System.Drawing.Color.Transparent;
            this.Delete_Btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Delete_Btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Delete_Btn.BackgroundImage")));
            this.Delete_Btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_Btn.ButtonText = "حذف";
            this.Delete_Btn.ButtonTextMarginLeft = 0;
            this.Delete_Btn.ColorContrastOnClick = 45;
            this.Delete_Btn.ColorContrastOnHover = 45;
            this.Delete_Btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Delete_Btn.CustomizableEdges = borderEdges4;
            this.Delete_Btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Delete_Btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_Btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_Btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_Btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Delete_Btn.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Delete_Btn.ForeColor = System.Drawing.Color.White;
            this.Delete_Btn.IconLeft = null;
            this.Delete_Btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Delete_Btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_Btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Delete_Btn.IconMarginLeft = 11;
            this.Delete_Btn.IconPadding = 10;
            this.Delete_Btn.IconRight = ((System.Drawing.Image)(resources.GetObject("Delete_Btn.IconRight")));
            this.Delete_Btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Delete_Btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_Btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Delete_Btn.IconSize = 25;
            this.Delete_Btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Delete_Btn.IdleBorderRadius = 33;
            this.Delete_Btn.IdleBorderThickness = 1;
            this.Delete_Btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Delete_Btn.IdleIconLeftImage = null;
            this.Delete_Btn.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Delete_Btn.IdleIconRightImage")));
            this.Delete_Btn.IndicateFocus = true;
            this.Delete_Btn.Location = new System.Drawing.Point(319, 417);
            this.Delete_Btn.Name = "Delete_Btn";
            this.Delete_Btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_Btn.OnDisabledState.BorderRadius = 35;
            this.Delete_Btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_Btn.OnDisabledState.BorderThickness = 1;
            this.Delete_Btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_Btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_Btn.OnDisabledState.IconLeftImage = null;
            this.Delete_Btn.OnDisabledState.IconRightImage = null;
            this.Delete_Btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Delete_Btn.onHoverState.BorderRadius = 35;
            this.Delete_Btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_Btn.onHoverState.BorderThickness = 1;
            this.Delete_Btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Delete_Btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Delete_Btn.onHoverState.IconLeftImage = null;
            this.Delete_Btn.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Delete_Btn.onHoverState.IconRightImage")));
            this.Delete_Btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Delete_Btn.OnIdleState.BorderRadius = 35;
            this.Delete_Btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_Btn.OnIdleState.BorderThickness = 1;
            this.Delete_Btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Delete_Btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Delete_Btn.OnIdleState.IconLeftImage = null;
            this.Delete_Btn.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Delete_Btn.OnIdleState.IconRightImage")));
            this.Delete_Btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Delete_Btn.OnPressedState.BorderRadius = 35;
            this.Delete_Btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_Btn.OnPressedState.BorderThickness = 1;
            this.Delete_Btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Delete_Btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Delete_Btn.OnPressedState.IconLeftImage = null;
            this.Delete_Btn.OnPressedState.IconRightImage = null;
            this.Delete_Btn.Size = new System.Drawing.Size(113, 35);
            this.Delete_Btn.TabIndex = 366;
            this.Delete_Btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Delete_Btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Delete_Btn.TextMarginLeft = 0;
            this.Delete_Btn.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Delete_Btn.UseDefaultRadiusAndThickness = true;
            this.Delete_Btn.Visible = false;
            this.Delete_Btn.Click += new System.EventHandler(this.Delete_Btn_Click);
            this.Delete_Btn.MouseEnter += new System.EventHandler(this.Action_Buttons_MouseHover);
            this.Delete_Btn.MouseLeave += new System.EventHandler(this.Action_Buttons_MouseLeave);
            this.Delete_Btn.MouseHover += new System.EventHandler(this.Action_Buttons_MouseHover);
            // 
            // Guna2Button1
            // 
            this.Guna2Button1.AllowAnimations = true;
            this.Guna2Button1.AllowMouseEffects = true;
            this.Guna2Button1.AllowToggling = false;
            this.Guna2Button1.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.Guna2Button1.AnimationSpeed = 200;
            this.Guna2Button1.AutoGenerateColors = false;
            this.Guna2Button1.AutoRoundBorders = true;
            this.Guna2Button1.AutoSizeLeftIcon = true;
            this.Guna2Button1.AutoSizeRightIcon = true;
            this.Guna2Button1.BackColor = System.Drawing.Color.Transparent;
            this.Guna2Button1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button1.BackgroundImage")));
            this.Guna2Button1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button1.ButtonText = "جديد";
            this.Guna2Button1.ButtonTextMarginLeft = 0;
            this.Guna2Button1.ColorContrastOnClick = 45;
            this.Guna2Button1.ColorContrastOnHover = 45;
            this.Guna2Button1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.Guna2Button1.CustomizableEdges = borderEdges5;
            this.Guna2Button1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Guna2Button1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Guna2Button1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Guna2Button1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Guna2Button1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Guna2Button1.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Guna2Button1.ForeColor = System.Drawing.Color.White;
            this.Guna2Button1.IconLeft = null;
            this.Guna2Button1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Guna2Button1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Guna2Button1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Guna2Button1.IconMarginLeft = 11;
            this.Guna2Button1.IconPadding = 10;
            this.Guna2Button1.IconRight = ((System.Drawing.Image)(resources.GetObject("Guna2Button1.IconRight")));
            this.Guna2Button1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Guna2Button1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Guna2Button1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Guna2Button1.IconSize = 25;
            this.Guna2Button1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button1.IdleBorderRadius = 33;
            this.Guna2Button1.IdleBorderThickness = 1;
            this.Guna2Button1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button1.IdleIconLeftImage = null;
            this.Guna2Button1.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button1.IdleIconRightImage")));
            this.Guna2Button1.IndicateFocus = true;
            this.Guna2Button1.Location = new System.Drawing.Point(167, 417);
            this.Guna2Button1.Name = "Guna2Button1";
            this.Guna2Button1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Guna2Button1.OnDisabledState.BorderRadius = 35;
            this.Guna2Button1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button1.OnDisabledState.BorderThickness = 1;
            this.Guna2Button1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Guna2Button1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Guna2Button1.OnDisabledState.IconLeftImage = null;
            this.Guna2Button1.OnDisabledState.IconRightImage = null;
            this.Guna2Button1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Guna2Button1.onHoverState.BorderRadius = 35;
            this.Guna2Button1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button1.onHoverState.BorderThickness = 1;
            this.Guna2Button1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Guna2Button1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Guna2Button1.onHoverState.IconLeftImage = null;
            this.Guna2Button1.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button1.onHoverState.IconRightImage")));
            this.Guna2Button1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button1.OnIdleState.BorderRadius = 35;
            this.Guna2Button1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button1.OnIdleState.BorderThickness = 1;
            this.Guna2Button1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Guna2Button1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Guna2Button1.OnIdleState.IconLeftImage = null;
            this.Guna2Button1.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Guna2Button1.OnIdleState.IconRightImage")));
            this.Guna2Button1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Guna2Button1.OnPressedState.BorderRadius = 35;
            this.Guna2Button1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Guna2Button1.OnPressedState.BorderThickness = 1;
            this.Guna2Button1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Guna2Button1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Guna2Button1.OnPressedState.IconLeftImage = null;
            this.Guna2Button1.OnPressedState.IconRightImage = null;
            this.Guna2Button1.Size = new System.Drawing.Size(113, 35);
            this.Guna2Button1.TabIndex = 367;
            this.Guna2Button1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Guna2Button1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Guna2Button1.TextMarginLeft = 0;
            this.Guna2Button1.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Guna2Button1.UseDefaultRadiusAndThickness = true;
            this.Guna2Button1.Visible = false;
            this.Guna2Button1.MouseEnter += new System.EventHandler(this.Action_Buttons_MouseHover);
            this.Guna2Button1.MouseLeave += new System.EventHandler(this.Action_Buttons_MouseLeave);
            this.Guna2Button1.MouseHover += new System.EventHandler(this.Action_Buttons_MouseHover);
            // 
            // Search_Btn
            // 
            this.Search_Btn.AllowAnimations = true;
            this.Search_Btn.AllowMouseEffects = true;
            this.Search_Btn.AllowToggling = false;
            this.Search_Btn.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.Search_Btn.AnimationSpeed = 200;
            this.Search_Btn.AutoGenerateColors = false;
            this.Search_Btn.AutoRoundBorders = true;
            this.Search_Btn.AutoSizeLeftIcon = true;
            this.Search_Btn.AutoSizeRightIcon = true;
            this.Search_Btn.BackColor = System.Drawing.Color.Transparent;
            this.Search_Btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Search_Btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Search_Btn.BackgroundImage")));
            this.Search_Btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Search_Btn.ButtonText = "بحث";
            this.Search_Btn.ButtonTextMarginLeft = 0;
            this.Search_Btn.ColorContrastOnClick = 45;
            this.Search_Btn.ColorContrastOnHover = 45;
            this.Search_Btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.Search_Btn.CustomizableEdges = borderEdges6;
            this.Search_Btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Search_Btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Search_Btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Search_Btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Search_Btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Search_Btn.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Search_Btn.ForeColor = System.Drawing.Color.White;
            this.Search_Btn.IconLeft = null;
            this.Search_Btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Search_Btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Search_Btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Search_Btn.IconMarginLeft = 11;
            this.Search_Btn.IconPadding = 10;
            this.Search_Btn.IconRight = ((System.Drawing.Image)(resources.GetObject("Search_Btn.IconRight")));
            this.Search_Btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Search_Btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Search_Btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Search_Btn.IconSize = 25;
            this.Search_Btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Search_Btn.IdleBorderRadius = 33;
            this.Search_Btn.IdleBorderThickness = 1;
            this.Search_Btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Search_Btn.IdleIconLeftImage = null;
            this.Search_Btn.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Search_Btn.IdleIconRightImage")));
            this.Search_Btn.IndicateFocus = true;
            this.Search_Btn.Location = new System.Drawing.Point(167, 417);
            this.Search_Btn.Name = "Search_Btn";
            this.Search_Btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Search_Btn.OnDisabledState.BorderRadius = 35;
            this.Search_Btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Search_Btn.OnDisabledState.BorderThickness = 1;
            this.Search_Btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Search_Btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Search_Btn.OnDisabledState.IconLeftImage = null;
            this.Search_Btn.OnDisabledState.IconRightImage = null;
            this.Search_Btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Search_Btn.onHoverState.BorderRadius = 35;
            this.Search_Btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Search_Btn.onHoverState.BorderThickness = 1;
            this.Search_Btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Search_Btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Search_Btn.onHoverState.IconLeftImage = null;
            this.Search_Btn.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Search_Btn.onHoverState.IconRightImage")));
            this.Search_Btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Search_Btn.OnIdleState.BorderRadius = 35;
            this.Search_Btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Search_Btn.OnIdleState.BorderThickness = 1;
            this.Search_Btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Search_Btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Search_Btn.OnIdleState.IconLeftImage = null;
            this.Search_Btn.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Search_Btn.OnIdleState.IconRightImage")));
            this.Search_Btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Search_Btn.OnPressedState.BorderRadius = 35;
            this.Search_Btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Search_Btn.OnPressedState.BorderThickness = 1;
            this.Search_Btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Search_Btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Search_Btn.OnPressedState.IconLeftImage = null;
            this.Search_Btn.OnPressedState.IconRightImage = null;
            this.Search_Btn.Size = new System.Drawing.Size(113, 35);
            this.Search_Btn.TabIndex = 368;
            this.Search_Btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Search_Btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Search_Btn.TextMarginLeft = 0;
            this.Search_Btn.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Search_Btn.UseDefaultRadiusAndThickness = true;
            this.Search_Btn.Visible = false;
            this.Search_Btn.Click += new System.EventHandler(this.Search_Btn_Click);
            this.Search_Btn.MouseEnter += new System.EventHandler(this.Action_Buttons_MouseHover);
            this.Search_Btn.MouseLeave += new System.EventHandler(this.Action_Buttons_MouseLeave);
            this.Search_Btn.MouseHover += new System.EventHandler(this.Action_Buttons_MouseHover);
            // 
            // Option_Btn
            // 
            this.Option_Btn.AllowAnimations = true;
            this.Option_Btn.AllowMouseEffects = true;
            this.Option_Btn.AllowToggling = false;
            this.Option_Btn.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.Option_Btn.AnimationSpeed = 200;
            this.Option_Btn.AutoGenerateColors = false;
            this.Option_Btn.AutoRoundBorders = true;
            this.Option_Btn.AutoSizeLeftIcon = true;
            this.Option_Btn.AutoSizeRightIcon = true;
            this.Option_Btn.BackColor = System.Drawing.Color.Transparent;
            this.Option_Btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Option_Btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Option_Btn.BackgroundImage")));
            this.Option_Btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Option_Btn.ButtonText = "";
            this.Option_Btn.ButtonTextMarginLeft = 0;
            this.Option_Btn.ColorContrastOnClick = 45;
            this.Option_Btn.ColorContrastOnHover = 45;
            this.Option_Btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.Option_Btn.CustomizableEdges = borderEdges7;
            this.Option_Btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Option_Btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Option_Btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Option_Btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Option_Btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Option_Btn.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Option_Btn.ForeColor = System.Drawing.Color.White;
            this.Option_Btn.IconLeft = null;
            this.Option_Btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Option_Btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Option_Btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Option_Btn.IconMarginLeft = 11;
            this.Option_Btn.IconPadding = 15;
            this.Option_Btn.IconRight = ((System.Drawing.Image)(resources.GetObject("Option_Btn.IconRight")));
            this.Option_Btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Option_Btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Option_Btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Option_Btn.IconSize = 25;
            this.Option_Btn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Option_Btn.IdleBorderRadius = 33;
            this.Option_Btn.IdleBorderThickness = 1;
            this.Option_Btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Option_Btn.IdleIconLeftImage = null;
            this.Option_Btn.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Option_Btn.IdleIconRightImage")));
            this.Option_Btn.IndicateFocus = true;
            this.Option_Btn.Location = new System.Drawing.Point(758, 429);
            this.Option_Btn.Name = "Option_Btn";
            this.Option_Btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Option_Btn.OnDisabledState.BorderRadius = 50;
            this.Option_Btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Option_Btn.OnDisabledState.BorderThickness = 1;
            this.Option_Btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Option_Btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Option_Btn.OnDisabledState.IconLeftImage = null;
            this.Option_Btn.OnDisabledState.IconRightImage = null;
            this.Option_Btn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Option_Btn.onHoverState.BorderRadius = 50;
            this.Option_Btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Option_Btn.onHoverState.BorderThickness = 1;
            this.Option_Btn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Option_Btn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Option_Btn.onHoverState.IconLeftImage = null;
            this.Option_Btn.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Option_Btn.onHoverState.IconRightImage")));
            this.Option_Btn.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Option_Btn.OnIdleState.BorderRadius = 50;
            this.Option_Btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Option_Btn.OnIdleState.BorderThickness = 1;
            this.Option_Btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Option_Btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Option_Btn.OnIdleState.IconLeftImage = null;
            this.Option_Btn.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Option_Btn.OnIdleState.IconRightImage")));
            this.Option_Btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Option_Btn.OnPressedState.BorderRadius = 50;
            this.Option_Btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Option_Btn.OnPressedState.BorderThickness = 1;
            this.Option_Btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Option_Btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Option_Btn.OnPressedState.IconLeftImage = null;
            this.Option_Btn.OnPressedState.IconRightImage = null;
            this.Option_Btn.Size = new System.Drawing.Size(50, 50);
            this.Option_Btn.TabIndex = 369;
            this.Option_Btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Option_Btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Option_Btn.TextMarginLeft = 0;
            this.Option_Btn.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Option_Btn.UseDefaultRadiusAndThickness = true;
            this.Option_Btn.Click += new System.EventHandler(this.Option_Btn_Click);
            // 
            // Back_Button
            // 
            this.Back_Button.AllowAnimations = true;
            this.Back_Button.AllowMouseEffects = true;
            this.Back_Button.AllowToggling = false;
            this.Back_Button.AnimationSpeed = 200;
            this.Back_Button.AutoGenerateColors = false;
            this.Back_Button.AutoRoundBorders = true;
            this.Back_Button.AutoSizeLeftIcon = true;
            this.Back_Button.AutoSizeRightIcon = true;
            this.Back_Button.BackColor = System.Drawing.Color.Transparent;
            this.Back_Button.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Back_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Back_Button.BackgroundImage")));
            this.Back_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Back_Button.ButtonText = "";
            this.Back_Button.ButtonTextMarginLeft = 0;
            this.Back_Button.ColorContrastOnClick = 45;
            this.Back_Button.ColorContrastOnHover = 45;
            this.Back_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.Back_Button.CustomizableEdges = borderEdges8;
            this.Back_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Back_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Back_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Back_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Back_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.Back_Button.Font = new System.Drawing.Font("Cairo", 8.999999F);
            this.Back_Button.ForeColor = System.Drawing.Color.White;
            this.Back_Button.IconLeft = null;
            this.Back_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Back_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Back_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Back_Button.IconMarginLeft = 11;
            this.Back_Button.IconPadding = 15;
            this.Back_Button.IconRight = ((System.Drawing.Image)(resources.GetObject("Back_Button.IconRight")));
            this.Back_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Back_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Back_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 15, 3);
            this.Back_Button.IconSize = 25;
            this.Back_Button.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Back_Button.IdleBorderRadius = 33;
            this.Back_Button.IdleBorderThickness = 1;
            this.Back_Button.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Back_Button.IdleIconLeftImage = null;
            this.Back_Button.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("Back_Button.IdleIconRightImage")));
            this.Back_Button.IndicateFocus = true;
            this.Back_Button.Location = new System.Drawing.Point(-5, -11);
            this.Back_Button.Name = "Back_Button";
            this.Back_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Back_Button.OnDisabledState.BorderRadius = 50;
            this.Back_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Back_Button.OnDisabledState.BorderThickness = 1;
            this.Back_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Back_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Back_Button.OnDisabledState.IconLeftImage = null;
            this.Back_Button.OnDisabledState.IconRightImage = null;
            this.Back_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Back_Button.onHoverState.BorderRadius = 50;
            this.Back_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Back_Button.onHoverState.BorderThickness = 1;
            this.Back_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(232)))), ((int)(((byte)(220)))));
            this.Back_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Back_Button.onHoverState.IconLeftImage = null;
            this.Back_Button.onHoverState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Back_Button.onHoverState.IconRightImage")));
            this.Back_Button.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Back_Button.OnIdleState.BorderRadius = 50;
            this.Back_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Back_Button.OnIdleState.BorderThickness = 1;
            this.Back_Button.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(188)))), ((int)(((byte)(152)))));
            this.Back_Button.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Back_Button.OnIdleState.IconLeftImage = null;
            this.Back_Button.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("Back_Button.OnIdleState.IconRightImage")));
            this.Back_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Back_Button.OnPressedState.BorderRadius = 50;
            this.Back_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Back_Button.OnPressedState.BorderThickness = 1;
            this.Back_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(166)))), ((int)(((byte)(134)))));
            this.Back_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Back_Button.OnPressedState.IconLeftImage = null;
            this.Back_Button.OnPressedState.IconRightImage = null;
            this.Back_Button.Size = new System.Drawing.Size(50, 50);
            this.Back_Button.TabIndex = 370;
            this.Back_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Back_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Back_Button.TextMarginLeft = 0;
            this.Back_Button.TextPadding = new System.Windows.Forms.Padding(-5, 0, 5, 0);
            this.Back_Button.UseDefaultRadiusAndThickness = true;
            this.Back_Button.Click += new System.EventHandler(this.Back_Button_Click);
            // 
            // DisableLockBtn
            // 
            this.DisableLockBtn.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.DisableLockBtn.Cursor = System.Windows.Forms.Cursors.No;
            this.DisableLockBtn.Enabled = false;
            this.DisableLockBtn.Image = ((System.Drawing.Image)(resources.GetObject("DisableLockBtn.Image")));
            this.DisableLockBtn.Location = new System.Drawing.Point(52, 2);
            this.DisableLockBtn.Name = "DisableLockBtn";
            this.DisableLockBtn.Size = new System.Drawing.Size(740, 409);
            this.DisableLockBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.DisableLockBtn.TabIndex = 371;
            this.DisableLockBtn.TabStop = false;
            this.DisableLockBtn.Visible = false;
            this.DisableLockBtn.Click += new System.EventHandler(this.DisableLockBtn_Click);
            // 
            // MasterUC
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.DisableLockBtn);
            this.Controls.Add(this.Back_Button);
            this.Controls.Add(this.Search_Btn);
            this.Controls.Add(this.Delete_Btn);
            this.Controls.Add(this.Save_Btn);
            this.Controls.Add(this.New_Btn);
            this.Controls.Add(this.Guna2Button1);
            this.Controls.Add(this.Guna2Button3);
            this.Controls.Add(this.Panel1);
            this.Controls.Add(this.Option_Btn);
            this.Name = "MasterUC";
            this.Size = new System.Drawing.Size(810, 468);
            this.SizeChanged += new System.EventHandler(this.MasterUC_SizeChanged);
            ((System.ComponentModel.ISupportInitialize)(this.DisableLockBtn)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        internal System.Windows.Forms.Panel Panel1;
        internal System.Windows.Forms.Timer Options_Tmr;
        internal A7MD_Library.NewComponent.A2SAnimator A2SAnimator1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton New_Btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Save_Btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Guna2Button3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Delete_Btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Guna2Button1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Search_Btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Option_Btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Back_Button;
        private System.Windows.Forms.PictureBox DisableLockBtn;
    }
}
